[build]
  command = "npm run build"
  publish = ".output/public"

[functions]
  directory = ".netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nuxt"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nuxt"
  status = 200